#ifndef _ERROR_CODE_H_
#define _ERROR_CODE_H_
enum
{
   ERROR_CODE_SUCC = 0, // for general errors
   ERROR_CODE_UNIMPLEMENTED ,
   ERROR_CODE_MEM_ALLOC_FAIL ,
   ERROR_CODE_TIME_OUT,
};

enum
{
    ERROR_PROTOCOL_GENERAL_BEGIN = 0x1000 ,
    ERROR_PROTOCOL_GENERAL_INIT_ERROR , // for protocol errors
    ERROR_PROTOCOL_GENERAL_CHECK_ERROR ,
    ERROR_PROTOCOL_GENERAL_INVALID_STATE ,
    ERROR_PROTOCOL_GENERAL_RESOURCE_UNAVAILABE ,
    ERROR_PROTOCOL_GENERAL_SENSOR_STATE ,
    
    ERROR_PROTOCOL_SG_BEGIN = 0x2000 ,
    ERROR_PROTOCOL_SG_SHELF_EMPTY ,
    ERROR_PROTOCOL_SG_SHELF_PUSHTO ,
    ERROR_PROTOCOL_SG_SHELF_FULL ,

    ERROR_PROTOCOL_SZ_BEGIN = 0x3000 ,
    ERROR_PROTOCOL_SZ_BOX_EMPTY ,
    ERROR_PROTOCOL_SZ_DRAW_FAILURE ,
    ERROR_PROTOCOL_SZ_DISCARD_FAILURE ,

    ERROR_PROTOCOL_JY_BEGIN = 0x4000 ,
    ERROR_PROTOCOL_JY_GHX_CLEAN_FAILURE ,
    ERROR_PROTOCOL_JY_JYZ_BUSY ,
    
    ERROR_PROTOCOL_CZ_BEGIN = 0x5000 ,
};

#define MAKE_ERROR_CODE(sensorinfo,section) ((sensorinfo<<0) | (0<<16)) // current no section info to report
#define MAKE_SENSOR_FLAG(sensorinfo) (1<<sensorinfo)
#endif
